# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  config.vm.boot_timeout = 600

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "virtualbox"

  config.vm.network :private_network, ip: "192.168.33.12"
  config.vm.network :forwarded_port, guest: 80, host: 8081
  config.vm.network :forwarded_port, id: 'ssh', guest: 22, host: 2322, auto_correct: false,  d: "ssh"

  config.vm.synced_folder "../html", "/var/www/html", group: "www-data", owner: "www-data", create: true
  config.vm.synced_folder "../scripts", "/opt/scripts", group: "www-data", owner: "www-data", create: true
  config.vm.synced_folder "../db_dump", "/var/www/db_dump", group: "www-data", owner: "www-data", create: true

  # Launch virtualbox GUI window
  config.vm.provider "virtualbox" do |v|
    v.name = "humanface"
    v.gui = false
    v.memory = 1024
  end

  # Copy Nginx default configuration to a location to be handled by the provisioner
  config.vm.provision "file", source: "provision/nginx/default", destination: "/tmp/nginx/sites-available/default"

  config.vm.provision :shell, :path => "provision/provision.sh"
end
